version: '3.9'

services:

  app:
    container_name: kawa
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: czernika/kawa-8.0
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 80:80
    environment:
      WP_CLI_PACKAGES_DIR: /var/www/html/.wp-cli/packages
      WP_CLI_CACHE_DIR: /var/www/html/.wp-cli/cache
      APP_ADMIN_USER: ${APP_ADMIN_USER}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_URL: ${APP_URL:-http://127.0.0.1}
      APP_LOCALE: ${APP_LOCALE:-en_US}
      APP_TITLE: ${APP_TITLE:-WordPress}
      DB_NAME: ${DB_NAME:-wolat}
      DB_USER: ${DB_USER:-wolat}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_PREFIX: ${DB_PREFIX:-wp_}
      IS_BEDROCK: 0
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bedrock

  mysql:
    container_name: kawa-db
    image: mysql:8
    volumes:
      - kawa-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_HOST: '127.0.0.1'
      MYSQL_DATABASE: ${DB_NAME:-wolat}
      MYSQL_USER: ${DB_USER:-wolat}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    cap_add:
      - SYS_NICE
    networks:
      - bedrock
    restart: always

networks:
  bedrock:

volumes:
  kawa-mysql:
    driver: local