version: '3.9'

services:

  app:
    container_name: kawa
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: czernika/kawa-8.0
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 80:80
    environment:
      WP_CLI_PACKAGES_DIR: /var/www/html/.wp-cli/packages
      APP_URL: ${WP_HOME}
      APP_ADMIN_USER: 'wolat'
      APP_ADMIN_EMAIL: 'wolat@example.com'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bedrock

  mysql:
    container_name: kawa-db
    image: mysql:8
    volumes:
      - kawa-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '127.0.0.1'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    cap_add:
      - SYS_NICE
    networks:
      - bedrock
    restart: always

networks:
  bedrock:

volumes:
  kawa-mysql:
    driver: local